"""add unique constraint to booking_slot_id

Revision ID: 975ca27f6266
Revises: 642660d88000
Create Date: 2025-12-03 19:55:16.592855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975ca27f6266'
down_revision: Union[str, Sequence[str], None] = '642660d88000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'restaurant_booking', ['booking_slot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_booking', type_='unique')
    # ### end Alembic commands ###
