"""Add image_url to restaurant

Revision ID: 9fd49429c94e
Revises: da9b6e070598
Create Date: 2025-11-25 23:02:30.591273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd49429c94e'
down_revision: Union[str, Sequence[str], None] = 'da9b6e070598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'image_url')
    # ### end Alembic commands ###
